repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      # removes trailing whitespace
    - id: trailing-whitespace
      exclude: '^LICENSE$'
    - id: end-of-file-fixer
      exclude: '^LICENSE$'
      # linting tool config: .flake8
    - id: flake8
      # guards the master branch by default
    - id: no-commit-to-branch
    # code formatter
    # linting tool config: pyproject.toml
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3.10.12
    # linting tool config: .pylintrc
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
    -   id: pylint
        # args: ["--ignore-patterns=test*", "--py3k"]
        args: ["--ignore-patterns=test*"]
