version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - ./csv_api:/csv_api
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: postgres://postgres:1234@db:5432/employee
    networks :
      - csv_netw

  db:
    image: postgres:13
    container_name: localdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: employee
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on: [web]
    networks :
      - csv_netw

networks:
  csv_netw:
    driver : bridge
    name : csv_netw

volumes:
  pgdata:
