version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - ./csv_api:/csv_api
    environment:
      FLASK_APP: run.py
      FLASK_ENV: production
      FLASK_DEBUG: 1 
      S3_BUCKET: csv-api-employee-db
      LOCAL_CSV_PATH: csv_files
